[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
softbuffer = "0.2.0"
tiny-skia = "0.8.2"
winit = "0.27.5"
